server:
  port: 8763
spring:
  application:
    name: mark-eureka-client-provider
eureka:
  client:
    serviceUrl:
      defaultZone:   http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
zuul:
  routes:
    service-name:
      path: mark-eureka-client-consumer
      service-id: mark-eureka-client-consumer